Feature/hair days filter
Tillytaly/Good-Hair-Day-App pull request #3
Opened 2022-05-29 15:34 UTC by Tillytaly

2022-05-29 16:56 UTC, ProteanCode requested changes

2022-05-29 16:56 UTC, ProteanCode commented on src/Components/HairDays/HDsHeader.js
> +import HDsFilterBtn from "./Header/HDsFilterBtn";
Zignoruj te uwagę bo Ci o niej wcześniej nie pisałem a jest trochę zależna od wewnętrznych standardów projektowych

2022-05-29 16:56 UTC, ProteanCode commented on src/Components/HairDays/Header/HDsFilterOptions.js
> +    setFilterOptions((prevOptions) => {
prevFilterOptions

2022-05-29 16:56 UTC, ProteanCode commented on src/Components/HairDays/Header/HDsFilterOptions.js
> +        newYearState.years[event.target.id].checked = event.target.checked;
ustaw kolejno false i true zamiast !event.target.checked i event.target.checked

2022-05-29 16:56 UTC, ProteanCode commented on src/Components/HairDays/Header/HDsFilterOptions.js
> +    setIdOfCheckedYear(event.target.id);
W tym przypadku to nie jest błąd, ale pamiętaj, że komponent wyrenderuje się dwukrotnie (2 razy wywołujesz metody typu setState) w React 17 (możesz to zdebugować bodajże tworząc console.log w useEffect( () => { console.log('x'); }, [])

Gdyby Twój komponent w jakimś useEffect używał, np. zapytania do API które strzela w serwer po informacje to ten CR by tu nie przeszedł bo zrobiła byś prawdopodobnie 2 zapytania do serwera zamiast jednego.

W React 18 wprowadzono automatyczny batching, którego nie testowałem ale wcześniej można było się wspomóc metodą `unstable_batchedUpdates`

https://reactjs.org/blog/2022/03/29/react-v18.html#new-feature-automatic-batching
https://github.com/reactwg/react-18/discussions/21

2022-05-29 16:56 UTC, ProteanCode commented on src/Components/HairDays/Header/HDsFilterOptions.js
> +    setFilterOptions((prevOptions) => {
prevFilterOptions

2022-05-29 16:56 UTC, ProteanCode commented on src/Components/HairDays/Header/HDsFilterOptions.js
> +      if (idOfCheckedMonth.length > 0) {
Sama obecność klucza nie powoduje, że kod się nie wysypie.

Spróbuj z
`Object.keys(newMonthState.months).indexOf(idOfCheckedMonth) >= 0`

2022-05-29 16:56 UTC, ProteanCode commented on src/Components/HairDays/Header/HDsMonths.js
> +          className="HDs-checkbox-container"
Tu chyba classname powinno być z małych

Klasy cssowe zawsze są z małych liter w projektach.

Zignoruj te uwagę jeśli chcesz bo trochę się tu czepiam, ale jak będziesz robić **kolejny projekt** (nie ten), to znajdź jakieś przykładowe ISO standardu pisania w SASSie

Tu jest przykład:
https://bradfrost.com/blog/post/css-architecture-for-design-systems/

Bezpośrednio zalinkowany na: https://sass-lang.com/styleguide/code

Nie chodzi tu o to czy to jest dobre ISO czy nie, ale o to, by jakiekolwiek było.

2022-05-29 16:56 UTC, ProteanCode commented on src/Components/NewHairDay/Header/NHDOptionsForm.js
> +          className = "NHD-checkbox-container"
Jeżeli zmieniasz nazwę komponentu to nazwa klasy powinna też być odpowiednio `ui-checkbox-container`

Prawdopodobnie kod ostylowania tej klasy też będzie trzeba przenieść do innego pliku bo nie jest to już NHD

2022-05-29 16:56 UTC, ProteanCode commented on src/Components/NewHairDay/Header/NHDOptionsForm.js
> +          className = "NHD-checkbox-container"
Zdarza się, że kod aplikacji wrapuje jeden komponent w drugim, i miała byś case:

```
<NHDCheckbox class="nhd-checkbox-container">
  <UICheckbox class="ui-checkbox-container">
  </UICheckbox>
</NHDCheckbox>
```

2022-05-29 16:56 UTC, ProteanCode commented on src/Components/UI/UICheckbox.js
> +          checked={props.checked && 'checked'}
Tu jest chyba mały błąd, kod `'checked'` zawsze będzie true bo to jest non-empty string i JS to ewaluuje jako 1 / true
Można to wywalić i zostawić samo `props.checked`

2022-05-29 16:56 UTC, ProteanCode commented on src/Sass/UI/_UICheckbox.scss
> +@include breakpoint(810px) {
Ten breakpoint jest dziwny

Zdecydowana większość stron webowych opiera się czy to na bootstrapie czy na jakimś innym frameworku, ale wszystkie dzielą podobne breakpointy 

https://polypane.app/blog/css-breakpoints-used-by-popular-css-frameworks/

W przyszłości ułóż sobie listę breakpointów pod którą zaprojektujesz RWD i staraj się operować jakimiś paddingami / marginami bo tu obsługujesz jakiś marginalny case których dla bardziej rozbudowanych stron było by dużo więcej

2022-05-29 16:56 UTC, ProteanCode commented on src/Sass/components/HairDays/_HDsHeader.scss
> +    height: 8rem;
Jest jakiś konkretny powód dla którego wysokość wyrażona jest w remach? Remów zazwyczaj używa się w jakiś małych liczbach w stylu 1.1025 albo 0.375

8 to dużo, domyślnie 1 rem to 16px czyli 128px, ale jak ktoś ma ustawienia systemu by rozmiar czcionko wynosił 125% to będzie już 160px

2022-05-29 16:56 UTC, ProteanCode commented on src/Sass/components/HairDays/Header/_HDsFilterOptions.scss
> +    width: 22rem;
W większości przypadków daje się coś w stylu width: 100% i operuje się paddingami na kontenerze wrapującym

2022-05-29 16:56 UTC, ProteanCode commented on src/Components/HairDays/Header/HDsYears.js
> +    <HDsCollapsable name="Year">
Nazwy pól są w notacji albo snake_case albo camelCase, żadna z nich nie zaczyna się dużą literą

2022-05-30 11:03 UTC, Tillytaly commented on src/Components/HairDays/Header/HDsFilterOptions.js
> +        newYearState.years[event.target.id].checked = event.target.checked;
false można faktycznie ustawić natomiast true powoduje tutaj, że nie można odznaczyć miesiąca tzn. że zawsze najmniej jeden musi być zaznaczony. W przypadku lat ma to sens natomiast moim założeniem (nie wiem czy słusznym) było, żeby jednak można było nie wybrać miesiąca i mieć dostęp do danych z całego roku.

2022-05-30 11:08 UTC, Tillytaly commented on src/Components/HairDays/Header/HDsFilterOptions.js
> +      if (idOfCheckedMonth.length > 0) {
Tutaj podobnie, indexOf(idOfCheckedMonth) >= 0 sprawdza czy dane state idOfCheckedMonth nie wskazuje na styczen, a ja przez length sprawdzam czy on wgl został updatowany i w kontekscie mozliwosci odznaczenia miesiąca wydaje mi się to ok.

2022-05-30 11:24 UTC, Tillytaly commented on src/Sass/components/HairDays/_HDsHeader.scss
> +    height: 8rem;
Powód jest chyba tylko strikte związany z tym, że jest mi wygodniej. W moim resecie css mam zmienioną wielkość standardową czcionki do 10px z 16 i dzięki temu u mnie 1 rem to 10 px.

2022-05-30 11:26 UTC, closed without merging